In [1]:
import pandas as pd
import ast

# Load the Excel file
df = pd.read_excel('D:/Car price prediction/DATASET/chennai_cars.xlsx')

# Function to flatten the nested dictionary in the first column
def flatten_column(column):
    flattened_data = []
    for item in column:
        # Convert string representation of dictionary to actual dictionary
        data_dict = ast.literal_eval(item)
        flattened_data.append(data_dict)
    return pd.DataFrame(flattened_data)

# Flatten the first column
flattened_df = flatten_column(df['new_car_detail'])

# Display the first few rows of the flattened data
print(flattened_df.head())

   it      ft         bt      km transmission  ownerNo      owner      oem  \
0   0  Petrol        SUV  20,000    Automatic        1  1st Owner      Kia
1   0  Petrol   Minivans  20,687       Manual        1  1st Owner   Maruti
2   0  Petrol        SUV  30,000       Manual        1  1st Owner   Nissan
3   0  Petrol  Hatchback  59,247       Manual        1  1st Owner  Hyundai
4   0  Petrol  Hatchback  50,000       Manual        1  1st Owner    Honda

            model  modelYear  centralVariantId                    variantName  \
0       Kia Sonet       2022              8654  Turbo DCT Anniversary Edition
1     Maruti Eeco       2015              4025         7 Seater Standard BSIV
2  Nissan Magnite       2021              8135          Turbo XV Premium BSVI
3     Hyundai i10       2015              1579                    Sportz 1.1L
4      Honda Jazz       2015              1341                  1.2 VX i VTEC

          price priceActual priceSaving priceFixedText  \
0  ₹ 11.50 Lakh                                   None
1   ₹ 4.15 Lakh                                   None
2   ₹ 7.50 Lakh                                   None
3   ₹ 3.98 Lakh                                   None
4   ₹ 5.50 Lakh                                   None

                                        trendingText
0  {'imgUrl': 'https://stimg.cardekho.com/used-ca...
1  {'imgUrl': 'https://stimg.cardekho.com/used-ca...
2  {'imgUrl': 'https://stimg.cardekho.com/used-ca...
3  {'imgUrl': 'https://stimg.cardekho.com/used-ca...
4  {'imgUrl': 'https://stimg.cardekho.com/used-ca...

In [2]:
import pandas as pd
import ast

# Load the Excel file
df = pd.read_excel('D:/Car price prediction/DATASET/chennai_cars.xlsx')

# Function to flatten the nested dictionary in the second column
def flatten_overview_column(column):
    flattened_data = []
    for item in column:
        # Convert string representation of dictionary to actual dictionary
        data_dict = ast.literal_eval(item)
        # Extract relevant information
        flat_dict = {
            'Registration Year': None,
            'Insurance Validity': None,
            'Fuel Type': None,
            'Seats': None,
            'Kms Driven': None,
            'RTO': None,
            'Ownership': None,
            'Engine Displacement': None,
            'Transmission': None,
            'Year of Manufacture': None
        }
        for entry in data_dict['top']:
            flat_dict[entry['key']] = entry['value']
        flattened_data.append(flat_dict)
    return pd.DataFrame(flattened_data)

# Flatten the second column
flattened_overview_df = flatten_overview_column(df['new_car_overview'])

# Display the first few rows of the flattened data
print(flattened_overview_df.head())

  Registration Year     Insurance Validity Fuel Type    Seats  Kms Driven  \
0              2022  Third Party insurance    Petrol  5 Seats  20,000 Kms
1          Feb 2015          Comprehensive    Petrol  7 Seats  20,687 Kms
2              2021  Third Party insurance    Petrol  5 Seats  30,000 Kms
3          May 2015          Comprehensive    Petrol  5 Seats  59,247 Kms
4              2015  Third Party insurance    Petrol  5 Seats  50,000 Kms

    RTO    Ownership Engine Displacement Transmission  Year of Manufacture
0  TN02  First Owner              998 cc    Automatic                 2022
1  TN04  First Owner             1196 cc       Manual                 2015
2  TN22  First Owner              999 cc       Manual                 2021
3  TN11  First Owner             1086 cc       Manual                 2015
4  KA03  First Owner             1199 cc       Manual                 2015

In [6]:
import pandas as pd
import ast

# Load the Excel file
df = pd.read_excel('D:/Car price prediction/DATASET/chennai_cars.xlsx')

# Function to flatten the nested dictionary in the third column
def flatten_features_column(column):
    flattened_data = []
    for item in column:
        # Convert string representation of dictionary to actual dictionary
        data_dict = ast.literal_eval(item)
        # Extract relevant features
        flat_dict = {
            'Comfort & Convenience': [],
            'Interior': [],
            'Exterior': [],
            'Safety': [],
            'Entertainment & Communication': []
        }
        for feature_category in data_dict['data']:
            category_name = feature_category['heading']
            for feature in feature_category['list']:
                flat_dict[category_name].append(feature['value'])
        flattened_data.append(flat_dict)
    return pd.DataFrame(flattened_data)

# Flatten the third column
flattened_features_df = flatten_features_column(df['new_car_feature'])

# Display the first few rows of the flattened data
print(flattened_features_df.head())

                               Comfort & Convenience  \
0  [Power Steering, Power Windows Front, Power Wi...
1  [Low Fuel Warning Light, Accessory Power Outle...
2  [Power Steering, Power Windows Front, Power Wi...
3  [Power Steering, Power Windows Front, Power Wi...
4  [Power Steering, Power Windows Front, Power Wi...

                                            Interior  \
0  [Air Conditioner, Heater, Adjustable Steering,...
1  [Heater, Digital Odometer, Electronic Multi Tr...
2  [Air Conditioner, Heater, Adjustable Steering,...
3  [Air Conditioner, Heater, Adjustable Steering,...
4  [Air Conditioner, Heater, Adjustable Steering,...

                                            Exterior  \
0  [Adjustable Head Lights, Fog Lights Front, Pow...
1  [Adjustable Head Lights, Manually Adjustable E...
2  [Adjustable Head Lights, Fog Lights Front, Pow...
3  [Adjustable Head Lights, Fog Lights Front, Man...
4  [Adjustable Head Lights, Fog Lights Front, Pow...

                                              Safety  \
0  [Anti Lock Braking System, Brake Assist, Cente...
1  [Anti Lock Braking System, Child Safety Locks,...
2  [Anti Lock Braking System, Brake Assist, Cente...
3  [Centeral Locking, Power Door Locks, Child Saf...
4  [Anti Lock Braking System, Centeral Locking, P...

                       Entertainment & Communication
0  [Radio, Speakers Front, Speakers Rear, Integra...
1                                                 []
2  [Radio, Speakers Front, Speakers Rear, Integra...
3  [Cd Player, Radio, Speakers Front, Speakers Re...
4  [Cd Player, Dvd Player, Radio, Speakers Front,...

In [7]:
import pandas as pd
import ast

# Load the Excel file
df = pd.read_excel('D:/Car price prediction/DATASET/chennai_cars.xlsx')

# Function to flatten the nested dictionary in the fourth column
def flatten_specs_column(column):
    flattened_data = []
    for item in column:
        # Convert string representation of dictionary to actual dictionary
        data_dict = ast.literal_eval(item)
        # Extract relevant specifications
        flat_dict = {
            'Mileage': None,
            'Engine': None,
            'Max Power': None,
            'Torque': None,
            'Wheel Size': None,
            'Seats': None
        }
        for spec_category in data_dict['top']:
            flat_dict[spec_category['key']] = spec_category['value']
        flattened_data.append(flat_dict)
    return pd.DataFrame(flattened_data)

# Flatten the fourth column
flattened_specs_df = flatten_specs_column(df['new_car_specs'])

# Display the first few rows of the flattened data
print(flattened_specs_df.head())

      Mileage   Engine  Max Power   Torque Wheel Size Seats
0        None   998 CC  118.36bhp    172nm         16     5
1  15.37 kmpl  1196 CC      73bhp    101Nm       None     7
2     20 kmpl   999 CC   98.63bhp    160Nm         16     5
3  19.81 kmpl  1086 CC   68.05bhp  99.04Nm       None     5
4   18.7 kmpl  1199 CC    88.7bhp    110Nm         15     5

In [8]:
import pandas as pd

# Concatenate DataFrames horizontally
merged_df = pd.concat([flattened_df, flattened_overview_df, flattened_features_df, flattened_specs_df], axis=1)

# Save to CSV
merged_df.to_csv('che_car_merged_dataset.csv', index=False)

In [2]:
import pandas as pd


# Load the CSV data
df = pd.read_csv('D:/Car price prediction/New dataset/che_car_merged_dataset.csv')

# Counting the number of elements in the list for specified columns
columns_to_count = ["Comfort & Convenience", "Interior", "Exterior", "Safety", "Entertainment & Communication"]
for column in columns_to_count:
    df[column] = df[column].apply(lambda x: len(eval(x)) if isinstance(x, str) else 0)

# Display the modified dataframe
print(df.head())
df.to_csv('che_car_merged_dataset1.csv', index=False)

   it      ft         bt      km transmission  ownerNo      owner      oem  \
0   0  Petrol        SUV  20,000    Automatic        1  1st Owner      Kia
1   0  Petrol   Minivans  20,687       Manual        1  1st Owner   Maruti
2   0  Petrol        SUV  30,000       Manual        1  1st Owner   Nissan
3   0  Petrol  Hatchback  59,247       Manual        1  1st Owner  Hyundai
4   0  Petrol  Hatchback  50,000       Manual        1  1st Owner    Honda

            model  modelYear  ...  Interior Exterior Safety  \
0       Kia Sonet       2022  ...        13       17     30
1     Maruti Eeco       2015  ...         5        4     13
2  Nissan Magnite       2021  ...        13       20     36
3     Hyundai i10       2015  ...         9        6     17
4      Honda Jazz       2015  ...        12       13     22

  Entertainment & Communication     Mileage   Engine  Max Power   Torque  \
0                             9         NaN   998 CC  118.36bhp    172nm
1                             0  15.37 kmpl  1196 CC      73bhp    101Nm
2                            11     20 kmpl   999 CC   98.63bhp    160Nm
3                             6  19.81 kmpl  1086 CC   68.05bhp  99.04Nm
4                            10   18.7 kmpl  1199 CC    88.7bhp    110Nm

  Wheel Size Seats.1
0         16       5
1        NaN       7
2         16       5
3        NaN       5
4         15       5

[5 rows x 38 columns]